### ISSUE TITLE
Adding this to the AUR

### ISSUE THREAD

**Issue by gabrielhidasy** [lpicanco/i3-autodisplay#4]
Hey, I made a PKGBUILD to add this to the AUR, its [here](https://gist.github.com/gabrielhidasy/7caeabce22a387daf38a8e51134750f1).

Could you add it there? It would make installing it and keeping up-to-date a lot easier for arch users. I can probably submit it too if you prefer.

**Comment by lpicanco** [comment]
Thanks, @gabrielhidasy!
I will add it there!

**Comment by gabrielhidasy** [comment]
Thanks!

**Comment by glitchcrab** [comment]
this is the first time i've seen this issue, but i added it to the AUR a while back https://aur.archlinux.org/packages/i3-autodisplay-bin/

**Comment by gabrielhidasy** [comment]
Thanks glitchcrab! It's working well, I've been using it from there.
