### ISSUE TITLE
Error: no such file or directory

### ISSUE THREAD

**Issue by Kerwood** [lpicanco/i3-autodisplay#9]
Am I the only one who cant run the 0.6 version?
I downloaded it from the release page, made it executable and ran it.
```
./i3-autodisplay-0.6-linux-amd64
zsh: no such file or directory: ./i3-autodisplay-0.6-linux-amd64
```

0.5 run fine, but it does not exit.

**Comment by lpicanco** [comment]
It was a problem with the build process. Can you check it again @Kerwood?

**Comment by Kerwood** [comment]
Works now, thank you.
